# Generated by Django 4.1.7 on 2024-01-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
            ],
        ),
    ]
